Oasys/Oasys/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('users/', include('users.urls')),
    path('', include('store.urls')),
    path('', include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Oasys/cart/urls.py
from django.urls import path

from .views import add_to_cart, cart, delete_cart_item, update_cart_item

app_name = 'cart'

urlpatterns = [
    path('', cart, name='cart'),
    path('add/<slug:item_slug>/', add_to_cart, name='add_to_cart'),
    path('delete/<slug:item_slug>/', delete_cart_item, name='delete_cart_item'),
    path('update_cart_item/', update_cart_item, name='update_cart_item'),
]

Oasys/checkout/urls.py
from django.urls import path

from .views import checkout, create_order, thank_you

app_name = 'checkout'

urlpatterns = [
    path('', checkout, name='checkout'),
    path('create-order/', create_order, name='create_order'),
    path('thank-you/<int:order_id>/', thank_you, name='thank_you'),
]

Oasys/store/urls.py
from django.urls import path

from .views import item_details, store, price, contact

app_name = 'store'


urlpatterns = [
    path('', store, name='home'),
    path('price/', price, name='price'),
    path('contact/', contact, name='contact'),
    path('<slug:item_slug>/', item_details, name='item_details'),
]

Oasys/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView,
                                       logout_then_login)
from django.urls import path, reverse_lazy

from .views import SignUp, feedback_processing, profile, user_orders, logout

app_name = 'users'

urlpatterns = [
     path('orders/', user_orders, name='user_orders'),
     path('profile/', profile, name='profile'),
     path('feedback-processing/', feedback_processing,
          name='feedback_processing'),
     path('auth/logout/',
          lambda request: logout_then_login(request, ''),
          name='logout'),
     path('auth/signup/', SignUp.as_view(), name='signup'),
     path('auth/login/',
          LoginView.as_view(template_name='users/login.html'),
          name='login'),
     path('auth/password_reset/',
          PasswordResetView.as_view(
               template_name='users/managment/password_reset_form.html',
               email_template_name='users/managment/password_reset_email.html',
               success_url='done/'),
               name='password_reset_form'),
     path('auth/password_reset/done/',
          PasswordResetDoneView.as_view(
               template_name='users/managment/password_reset_done.html'),
          name='password_reset_done'),
     path('auth/reset/done/',
          PasswordResetCompleteView.as_view(
               template_name='users/managment/reset_done.html'),
          name='reset_done'),
     path('auth/password_reset_confirm/<uidb64>/<token>/',
          PasswordResetConfirmView.as_view(
               template_name='users/managment/password_reset_confirm.html',
               success_url=reverse_lazy('users:reset_done')),
          name='password_reset_confirm'),
     path('auth/password_reset_complete/',
          PasswordResetCompleteView.as_view(
               template_name='users/managment/password_reset_complete.html'),
          name='password_reset_complete'),
     path('auth/password_change/',
          PasswordChangeView.as_view(
               template_name='users/managment/password_change_form.html',
               success_url='done/'),
          name='password_change'),
     path('auth/password_change/done/',
          PasswordChangeDoneView.as_view(
               template_name='users/managment/password_change_done.html'),
          name='password_change_done'),
]

Oasys/checkout/models.py
from django.contrib.auth.models import User
from django.db import models

from store.models import Item


class Order(models.Model):
    PAYMENT_METHOD_CHOICES = [
        ('cash_courier', 'Наличными курьеру'),
        ('card_courier', 'Картой курьеру'),
        ('card_online', 'Картой онлайн'),
    ]
    STATUS_CHOICES = [
        ('created', 'Создан'),
        ('processing', 'Обрабатывается'),
        ('shipped', 'Отправлен'),
        ('delivered', 'Доставлен'),
        ('canceled', 'Отменен'),
    ]
    payment_method = models.CharField(
        max_length=20,
        choices=PAYMENT_METHOD_CHOICES,
        verbose_name='Способ оплаты',
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='orders',
        verbose_name='Покупатель',
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания',
    )
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default='created',
        verbose_name='Статус',
    )

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'
        ordering = ['-created_at']

    @property
    def total_price(self):
        total_price = sum(
            order_item.total_price for order_item in self.items.all())
        return total_price

    def __str__(self):
        return f"Заказ номер {self.id} для {self.user}"


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        related_name='items',
        verbose_name='Заказ',
    )
    item = models.ForeignKey(
        Item, on_delete=models.CASCADE, verbose_name='Товар',)
    quantity = models.PositiveIntegerField(
        default=1, verbose_name='Количество',)
    price = models.DecimalField(
        max_digits=10, decimal_places=2, verbose_name='Цена',)

    class Meta:
        verbose_name = 'Товар в заказе'
        verbose_name_plural = 'Товары в заказе'

    @property
    def total_price(self):
        total_price = self.quantity * self.item.price
        return total_price

    def __str__(self):
        return f"{self.quantity} x {self.item.title} in Order {self.order.id}"


class ShippingAddress(models.Model):
    first_name = models.CharField(max_length=50, verbose_name='Имя',)
    last_name = models.CharField(max_length=50, verbose_name='Фамилия',)
    email = models.EmailField(verbose_name='Почта',)
    phone = models.CharField(max_length=20, verbose_name='Телефон',)
    address_line_1 = models.CharField(max_length=200, verbose_name='Адрес',)
    address_line_2 = models.CharField(max_length=200, blank=True, null=True, verbose_name='Адрес (дополнительно)',)
    order = models.OneToOneField(
        Order, on_delete=models.CASCADE, related_name='shipping_address', verbose_name='Заказ',)

    class Meta:
        verbose_name = 'Адрес доставки'
        verbose_name_plural = 'Адреса доставки'

    def __str__(self):
        return f"""
        {self.address_line_1} {self.address_line_2}
        Для: {self.first_name} {self.last_name},
        Почта: {self.email},
        Телефон: {self.phone}
        """

Oasys/checkout/forms.py
from django import forms

from .models import Order


class PlaceholderForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(PlaceholderForm, self).__init__(*args, **kwargs)
        for _, field in self.fields.items():
            field.widget.attrs['placeholder'] = field.help_text


class OrderCreateForm(PlaceholderForm):
    first_name = forms.CharField(max_length=100, help_text='Имя')
    last_name = forms.CharField(max_length=100, help_text='Фамилия')
    email = forms.EmailField(help_text='Email')
    phone = forms.CharField(max_length=20, help_text='Телефон')
    address_line_1 = forms.CharField(max_length=100, help_text='Адрес')
    address_line_2 = forms.CharField(
        max_length=100,
        required=False,
        help_text='Адрес (дополнительно)'
    )
    payment_method = forms.ChoiceField(choices=Order.PAYMENT_METHOD_CHOICES)

Oasys/checkout/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from cart.views import Cart
from .forms import OrderCreateForm
from .models import Order, OrderItem, ShippingAddress


@login_required
def checkout(request):
    """
    Представление чекаута.
    """
    cart = Cart.objects.get(user=request.user)
    form = OrderCreateForm()
    context = {'cart': cart, 'form': form}

    return render(request, 'checkout/checkout.html', context)


@login_required
def thank_you(request, order_id):
    """
    Страница благодарности за заказ.
    """
    order = get_object_or_404(Order, id=order_id, user=request.user)
    return render(request, 'checkout/thank_you.html', {'order': order})


@login_required
def create_order(request):
    """
    Создание экземпляров Order и ShippingAddress
    из формы и редирект в профиль пользователя,
    либо передаем форму обратно.
    """
    cart = get_object_or_404(Cart, user=request.user)

    if cart.items.exists() and request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = Order.objects.create(
                payment_method=form.cleaned_data['payment_method'],
                user=request.user,
            )

            ShippingAddress.objects.create(
                first_name=form.cleaned_data['first_name'],
                last_name=form.cleaned_data['last_name'],
                email=form.cleaned_data['email'],
                phone=form.cleaned_data['phone'],
                address_line_1=form.cleaned_data['address_line_1'],
                address_line_2=form.cleaned_data['address_line_2'],
                order=order,
            )

            for cart_item in cart.items.all():
                OrderItem.objects.create(
                    order=order,
                    item=cart_item.item,
                    quantity=cart_item.quantity,
                    price=cart_item.item.price
                )

            cart.clear()
            return redirect('checkout:thank_you', order_id=order.id)
    else:
        form = OrderCreateForm()
    messages.warning(
        request, 'Форма не была корректно обработана, введите данные еще раз')
    context = {'form': form, 'cart': cart}
    return render(request, 'checkout/checkout.html', context)

Oasys/templates/checkout/checkout.html
{% extends 'base.html' %}

{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static "css/checkout.css"%}" />
{% endblock %}

{% block content %}
<h1>Оформление заказа</h1>
{% if messages %}
<div class="messages-container">
  <ul class="messages">
    {% for message in messages %}
      <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
  </ul>
</div>
{% endif %}
<form method="post" action="{% url 'checkout:create_order'%}">
  {% csrf_token %}
  <section>
  <div class="row">
    <div class="col-md-8" style="width: 60%; padding-right: 20px;">
      <div><h2>Доставка</h2></div>
      {% for field in form %}
        {% if field.name != 'payment_method' %}
          <div class="form-group">
            {{ field }}
            <div class="text-danger error-message">
              {% for error in field.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          </div>
        {% endif %}
      {% endfor %}
    </div>
    <div class="col-md-4" style="width: 40%;">
      <h2>Ваш заказ</h2>
      {% if cart.items.exists %}
        <div class="table-wrapper">
          <table class="alt">
            <thead>
              <tr>
                <th>Название</th>
                <th>Количество</th>
                <th>Цена</th>
              </tr>
            </thead>
            <tbody>
              {% for cart_item in cart.items.all %}
              <tr>
                <td>{{ cart_item.item.title|truncatechars:20 }}</td>
                <td>
                    {{ cart_item.quantity }}
                </td>
                <td>{{ cart_item.total_price }}</td>
              </tr>
              {% endfor %}
            </tbody>
            <tfoot>
              <tr>
                <td colspan="2"></td>
                <td><b>{{ cart.total_price }}</b></td>
              </tr>
            </tfoot>
          </table>
        </div>
      {% else %}
        Корзина пустая
        <a href="{% url 'store:home' %}"  style="margin-bottom: 100px; margin-top: 50px;" class="button">Вернуться на главную</a>
      {% endif %}
      <div><h2>Выберите способ оплаты</h2></div>
      {{ form.payment_method }}
      <!-- Всплывающее окно для опции "Картой онлайн" -->
      {% include 'checkout/popup.html' %}
    </div>
  </section>
    <div class="actions" style="text-align: justify; margin-top: 100px;">
      <input type="reset" value="Сбросить" style="float: left;">
      {% if cart.items.exists %}
        <input type="submit" value="Оставить заказ" class="primary" style="float: right;">
      {% else %}
        <input type="submit" value="Оставить заказ" class="primary disabled" style="float: right;">
      {% endif %}
    </div>
  </div>
</form>
{% endblock %}

{% block js %}
<script src={% static "assets/js/checkout.js"%}></script>
<!-- PayPal JavaScript SDK -->
<script src="https://www.paypal.com/sdk/js?client-id=test&currency=USD"></script>
<script src={% static "assets/js/payment.js"%}></script>
{% endblock %}

Oasys/templates/checkout/popup.html
<div id="overlay" class="overlay"></div>
<div id="online-payment-info" class="hidden">
  <button id="close-btn">Закрыть</button>
  <h2 style="color: red;">НЕ ПЛАТИТЕ ЭТО ШУТКА</h2>
  <div id="paypal-button-container"></div>
  <h2 style="color: red;">НЕ ПЛАТИТЕ ЭТО ШУТКА</h2>
</div>

Oasys/templates/checkout/thank_you.html
{% extends 'base.html' %}

{% block content %}
<h2>Спасибо за ваш заказ!</h2>
<p><strong>Содержимое заказа:</strong>
{% for item in order.items.all %}
  <li>{{ item.quantity }} х {{ item.item.title }}</li>
{% endfor %}
<br>
<p>На сумму <b>{{ order.total_price }}</b> рублей.</p>
</p>
<p><strong>Привезем по адресу:</strong></p>
<p>{{ order.shipping_address }}</p>
<div>
  <a href="{% url 'users:user_orders' %}" class="button">Мои заказы</a>
</div>
{% endblock %}